-- Goal phases for the Log tab weight chart.
-- Run once: Supabase dashboard → SQL Editor → paste → Run.
-- Until this exists the app still works: the chart uses the goals row only,
-- and the Healthy Range / Start a new phase controls stay disabled.

create table if not exists public.goal_phases (
  id             bigint generated by default as identity primary key,
  user_id        text        not null,
  start_date     date        not null,
  end_date       date,                          -- null = the active phase
  start_weight   numeric     not null,
  target_weight  numeric     not null,          -- = start_weight for a maintain phase
  daily_calories integer,
  lbs_per_day    numeric     not null default 0, -- planned rate, fixed when the phase is saved
  range_low      numeric,                        -- healthy range (both equal = single baseline)
  range_high     numeric,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists goal_phases_user_start on public.goal_phases (user_id, start_date);

-- Access: the app has no login and scopes every query by user_id, like the
-- other tables. Before running, compare with weight_log's policies
-- (Authentication → Policies) and mirror those if they differ from this.
alter table public.goal_phases enable row level security;
create policy "goal_phases anon access" on public.goal_phases
  for all to anon using (true) with check (true);
grant select, insert, update, delete on public.goal_phases to anon;
